#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Create a release keystore for SwordFM and wire up signing.
#
#   ./tool/setup_release_signing.sh            # generate (fails if it exists)
#   ./tool/setup_release_signing.sh --force    # overwrite existing keystore
#
# Produces:
#   <KEYSTORE_DIR>/swordfm-release.p12   PKCS12 keystore (NEVER commit)
#   android/key.properties               wiring read by build.gradle.kts (git-ignored)
#
# IMPORTANT: back this keystore up offline. Losing it means you can never
# publish an update to the same Play Store listing again.
# ---------------------------------------------------------------------------
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KEYSTORE_DIR="${SWORDFM_KEYSTORE_DIR:-$HOME/keystores}"
KEYSTORE="$KEYSTORE_DIR/swordfm-release.p12"
ALIAS="${SWORDFM_KEY_ALIAS:-swordfm}"
PROPS="$REPO_ROOT/android/key.properties"
FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

if ! command -v keytool >/dev/null 2>&1; then
  echo "error: keytool not found. Install a JDK (e.g. openjdk-17-jdk)." >&2
  exit 1
fi

if [[ -f "$KEYSTORE" && $FORCE -eq 0 ]]; then
  echo "error: $KEYSTORE already exists. Use --force to overwrite." >&2
  exit 1
fi

read -r -s -p "Keystore password: " STORE_PASS; echo
read -r -s -p "Confirm password : " STORE_PASS2; echo
if [[ "$STORE_PASS" != "$STORE_PASS2" ]]; then
  echo "error: passwords do not match." >&2; exit 1
fi
if [[ ${#STORE_PASS} -lt 8 ]]; then
  echo "error: use at least 8 characters." >&2; exit 1
fi

mkdir -p "$KEYSTORE_DIR"

keytool -genkeypair -v \
  -keystore "$KEYSTORE" \
  -storetype PKCS12 \
  -keyalg RSA -keysize 2048 -validity 10950 \
  -alias "$ALIAS" \
  -storepass "$STORE_PASS" -keypass "$STORE_PASS" \
  -dname "CN=SwordFM, OU=Mobile, O=SwordFM, L=Dhaka, ST=Dhaka, C=BD"

umask 077
cat > "$PROPS" <<EOF
# Release signing — LOCAL ONLY, git-ignored (see android/.gitignore).
# Generated by tool/setup_release_signing.sh
storeFile=$KEYSTORE
storePassword=$STORE_PASS
keyAlias=$ALIAS
keyPassword=$STORE_PASS
EOF

echo
echo "✅ Keystore : $KEYSTORE"
echo "✅ Wiring   : $PROPS"
echo
echo "Fingerprint (record this in Play Console → App integrity):"
keytool -list -v -keystore "$KEYSTORE" -storepass "$STORE_PASS" -alias "$ALIAS" 2>/dev/null \
  | grep -E 'SHA1:|SHA256:' || true
echo
echo "⚠️  Back up $KEYSTORE offline. Losing it permanently blocks app updates."
