import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:archive/archive.dart';
import 'package:flutter/foundation.dart' show compute;
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:pdfx/pdfx.dart';
import 'package:video_player/video_player.dart';
import 'package:video_thumbnail/video_thumbnail.dart';
import '../screens/docx_reader_screen.dart';
import '../screens/image_viewer_screen.dart';
import '../screens/pdf_reader_screen.dart';
import '../screens/text_reader_screen.dart';
import '../screens/video_player_screen.dart';
import '../services/open_with_service.dart';
import '../theme/theme.dart';
import '../utils/file_utils.dart';

/// A collapsible panel that previews the selected file.
class PreviewPanel extends StatefulWidget {
  final FileItem? item;
  final double width;
  final double? height;

  /// Called when the header close button is tapped (dismisses the hosting
  /// bottom sheet, or collapses the side panel).
  final VoidCallback? onClose;

  /// Called when the user swipes horizontally on the panel to open full screen.
  final VoidCallback? onSwipe;

  const PreviewPanel({
    super.key,
    required this.item,
    required this.width,
    this.height,
    this.onClose,
    this.onSwipe,
  });

  @override
  State<PreviewPanel> createState() => _PreviewPanelState();
}

class _PreviewPanelState extends State<PreviewPanel> {
  String _content = '';
  bool _loading = false;
  String? _error;
  // PDF first-page thumbnail path (generated by pdfx) — non-null when ready.
  List<String> _pdfPageThumbs = const [];
  int _pdfPageCount = 0;
  /// Cap on how many pages we render in the preview to keep memory bounded.
  /// 20 pages × 640× ~900px JPEG ≈ 25-30 MB which is enough to read most
  /// book pages clearly on a phone; larger PDFs show the first 20 + an
  /// "open all N pages in reader" button.
  static const int _kPdfPreviewCap = 20;

  @override
  void initState() {
    super.initState();
    _loadContent();
  }

  @override
  void didUpdateWidget(covariant PreviewPanel oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.item?.path != widget.item?.path) {
      _loadContent();
    }
  }

  void _openFullScreen(FileItem item) {
    // PDFs get the in-app PdfReaderScreen (pinch-to-zoom, page nav, go-to-page)
    // — much better UX than the system default. DOCX gets the in-app
    // DocxReaderScreen (real formatting: headings, bold, lists, tables,
    // images). MD / text / code get a full-screen TextReaderScreen
    // (markdown for .md, monospaced + line numbers for everything else).
    // Videos get the in-app player. Archives/images/audio fall back to
    // the system default handler.
    if (item.isPdf) {
      Navigator.of(context).push(
        MaterialPageRoute(
          builder: (_) => PdfReaderScreen(filePath: item.path),
        ),
      );
      return;
    }
    if (item.isDocx) {
      Navigator.of(context).push(
        MaterialPageRoute(
          builder: (_) => DocxReaderScreen(filePath: item.path),
        ),
      );
      return;
    }
    if (item.isMarkdown || item.isText || item.isCode) {
      Navigator.of(context).push(
        MaterialPageRoute(
          builder: (_) => TextReaderScreen(filePath: item.path),
        ),
      );
      return;
    }
    if (item.isVideo) {
      Navigator.of(context).push(
        MaterialPageRoute(
          builder: (_) => VideoPlayerScreen(filePath: item.path),
        ),
      );
      return;
    }
    // Images get the in-app pinch-zoom viewer (double-tap zoom, rotate,
    // reset) instead of handing off to an external app.
    if (item.isImage) {
      Navigator.of(context).push(
        MaterialPageRoute(
          builder: (_) => ImageViewerScreen(filePath: item.path),
        ),
      );
      return;
    }
    OpenWithService.openDefault(item.path);
  }

  Future<void> _loadContent() async {
    if (widget.item == null) {
      setState(() {
        _content = '';
        _error = null;
        _pdfPageThumbs = const [];
        _pdfPageCount = 0;
      });
      return;
    }
    setState(() {
      _loading = true;
      _content = '';
      _error = null;
      _pdfPageThumbs = const [];
      _pdfPageCount = 0;
    });

    try {
      final path = widget.item!.path;
      if (widget.item!.isVideo) {
        // No text content for videos; the panel renders a thumbnail + play
        // overlay from the video file itself.
      } else if (widget.item!.isPdf) {
        // PDF preview: render every page (up to [_kPdfPreviewCap]) to a small
        // JPEG under the app's temp dir so the user can scroll through the
        // document in the preview panel. Cached on disk so a re-preview of
        // the same file is fast. Cannot run in a background isolate — pdfx
        // holds a native handle. Falls back to a metadata card if anything
        // throws.
        _pdfPageThumbs = const [];
        _pdfPageCount = 0;
        try {
          final doc = await PdfDocument.openFile(path);
          _pdfPageCount = doc.pagesCount;
          final pagesToRender =
              _pdfPageCount < _kPdfPreviewCap ? _pdfPageCount : _kPdfPreviewCap;
          final tmpDir =
              await Directory.systemTemp.createTemp('swordfm_pdf_');
          final thumbs = <String>[];
          for (var i = 1; i <= pagesToRender; i++) {
            final page = await doc.getPage(i);
            // 640px wide — wide enough that book text is comfortably
            // readable on a phone, sharp enough that zoom-in on a single
            // page stays legible. JPEG keeps the file small (50-200 KB
            // per page depending on content).
            final png = await page.render(
              width: 640,
              height: (page.height * 640 / page.width),
              format: PdfPageImageFormat.jpeg,
              backgroundColor: '#FFFFFF',
            );
            await page.close();
            if (png == null || png.bytes.isEmpty) continue;
            final out = File('${tmpDir.path}/page$i.jpg');
            await out.writeAsBytes(png.bytes);
            thumbs.add(out.path);
          }
          await doc.close();
          if (thumbs.isNotEmpty) {
            _pdfPageThumbs = thumbs;
          }
        } catch (_) {
          // PDF rendering failed — fall through to the metadata card.
        }
      } else if (widget.item!.isPptx) {
        // PPTX is a ZIP of slide XML files. Extract a list of slide titles
        // (or the first non-empty text per slide) for a structured preview.
        _content = await compute(pptxOutlineFromPath, path);
      } else if (widget.item!.isMarkdown) {
        _content = await compute(readTextCapped, path);
      } else if (widget.item!.extension.toLowerCase() == '.docx') {
        // DOCX is a ZIP binary — pull the text out in a background isolate so
        // the (potentially large) ZIP decode + XML regex never blocks the UI.
        _content = await compute(docxTextFromPath, path);
      } else if (widget.item!.isText || widget.item!.isCode) {
        _content = await compute(readTextCapped, path);
      }
    } catch (e) {
      setState(() {
        _error = 'Failed to load preview: $e';
      });
    } finally {
      if (mounted) {
        setState(() {
          _loading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final item = widget.item;
    if (item == null) {
      return const SizedBox.shrink();
    }

    final cs = Theme.of(context).colorScheme;

    return SizedBox(
      width: widget.width,
      height: widget.height,
      child: Card(
        margin: const EdgeInsets.all(8),
        color: cs.surfaceContainerHighest,
        child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header — NO GestureDetector wrapping this Row.
          // Each IconButton is an InkWell with its own TapGestureRecognizer
          // that wins the arena by being the deepest hit-test target.
          Container(
            color: cs.surfaceContainerHighest,
            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
            child: Row(
              children: [
                Icon(item.icon, color: item.iconColor, size: 20),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    item.name,
                    style: TextStyle(
                      color: cs.onSurface,
                      fontSize: 13,
                      fontWeight: FontWeight.w600,
                    ),
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
                IconButton(
                  icon: Icon(Icons.fullscreen, size: 20, color: cs.primary),
                  onPressed: () => _openFullScreen(item),
                  padding: const EdgeInsets.all(8),
                  constraints: const BoxConstraints(minWidth: 40, minHeight: 40),
                  tooltip: 'Open full screen',
                ),
                IconButton(
                  icon: Icon(Icons.close, size: 20, color: cs.onSurfaceVariant),
                  onPressed: widget.onClose ?? () {},
                  padding: const EdgeInsets.all(8),
                  constraints: const BoxConstraints(minWidth: 40, minHeight: 40),
                  tooltip: 'Close preview',
                ),
              ],
            ),
          ),
          const Divider(height: 1),
          // Content — no gesture detector here either
          Expanded(
            child: _loading
                ? const Center(child: CircularProgressIndicator())
                : _error != null
                ? Center(
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: Text(
                        _error!,
                        style: TextStyle(color: cs.error),
                        textAlign: TextAlign.center,
                      ),
                    ),
                  )
                : SingleChildScrollView(
                    padding: const EdgeInsets.all(12),
                    child: _buildPreview(),
                  ),
          ),
        ],
        ),
      ),
    );
  }

  Widget _buildPreview() {
    final item = widget.item!;
    final cs = Theme.of(context).colorScheme;
    if (item.isPdf) {
      if (_pdfPageThumbs.isNotEmpty) {
        final capped = _pdfPageCount > _kPdfPreviewCap;
        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            for (var i = 0; i < _pdfPageThumbs.length; i++)
              _PdfPagePreview(
                thumbPath: _pdfPageThumbs[i],
                pageIndex: i,
                pageCount: _pdfPageCount,
                capped: capped,
                maxPreview: _kPdfPreviewCap,
                onFullScreen: () => _openFullScreen(item),
              ),
            if (capped)
              Padding(
                padding: const EdgeInsets.only(top: 4),
                child: FilledButton.icon(
                  onPressed: () => _openFullScreen(item),
                  icon: const Icon(Icons.fullscreen, size: 16),
                  label: Text(
                      'Open all $_pdfPageCount pages in reader'),
                ),
              )
            else
              Padding(
                padding: const EdgeInsets.only(top: 4),
                child: Text(
                  'Tap any page to open in reader',
                  style: TextStyle(
                      color: cs.onSurfaceVariant, fontSize: 11),
                ),
              ),
          ],
        );
      }
      return _buildMetadataCard();
    }
    if (item.isPptx) {
      return GestureDetector(
        onTap: () => _openFullScreen(item),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(Icons.slideshow, size: 18, color: cs.primary),
                const SizedBox(width: 6),
                Text(
                  'Slides — tap to open',
                  style: TextStyle(
                      color: cs.onSurfaceVariant, fontSize: 11),
                ),
              ],
            ),
            const SizedBox(height: 6),
            Text(
              _content.isEmpty ? '[Loading slide list…]' : _content,
              style: TextStyle(
                color: cs.onSurface,
                fontSize: 12,
                fontFamily: 'monospace',
                height: 1.4,
              ),
            ),
          ],
        ),
      );
    }
    if (item.isVideo) {
      return _VideoPreviewTile(
        path: item.path,
        name: item.name,
        onFullScreen: () => _openFullScreen(item),
      );
    }
    if (item.isImage) {
      return _ImagePreviewTile(
        item: item,
        onFullScreen: () => _openFullScreen(item),
      );
    }
    if (item.isMarkdown) {
      return MarkdownBody(
        data: _content,
        styleSheet: MarkdownStyleSheet.fromTheme(Theme.of(context)).copyWith(
          p: TextStyle(color: cs.onSurface, fontSize: 13),
          code: TextStyle(
            color: cs.primary,
            fontFamily: 'monospace',
            fontSize: 12,
          ),
          codeblockDecoration: BoxDecoration(color: cs.surfaceContainerHighest),
        ),
      );
    }
    if (item.isText || item.extension.toLowerCase() == '.docx') {
      // DOCX preview: show the stripped text plus a button to open the
      // in-app reader. The full-screen button in the header does the same
      // thing; this just makes the preview tile itself tappable so users
      // don't have to hunt for the icon.
      if (item.extension.toLowerCase() == '.docx') {
        return GestureDetector(
          onTap: () => _openFullScreen(item),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              SelectableText(
                _content.isEmpty
                    ? '[No text content]'
                    : _content,
                style: TextStyle(
                  color: cs.onSurface,
                  fontSize: 12,
                  fontFamily: 'monospace',
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Tap to open in DOCX reader',
                style: TextStyle(
                  color: cs.primary,
                  fontSize: 11,
                  decoration: TextDecoration.underline,
                ),
              ),
            ],
          ),
        );
      }
      return SelectableText(
        _content,
        style: TextStyle(
          color: cs.onSurface,
          fontSize: 12,
          fontFamily: 'monospace',
        ),
      );
    }
    if (item.isDirectory) {
      return _buildMetadataCard();
    }
    // Unsupported types: metadata + open button
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        _buildMetadataCard(),
        const SizedBox(height: 12),
        Center(
          child: FilledButton.icon(
            onPressed: () async {
              try {
                await OpenWithService.openDefault(item.path);
              } catch (_) {
                if (mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(
                      content: const Text("We couldn't find an app that opens this file type"),
                      backgroundColor: cs.error,
                    ),
                  );
                }
              }
            },
            icon: const Icon(Icons.open_in_new, size: 16),
            label: const Text('Open with…'),
          ),
        ),
      ],
    );
  }

  Widget _buildMetadataCard() {
    final item = widget.item!;
    final cs = Theme.of(context).colorScheme;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Icon(item.icon, size: 40, color: item.iconColor),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    item.name,
                    style: TextStyle(
                      color: cs.onSurface,
                      fontSize: 13,
                      fontWeight: FontWeight.w600,
                    ),
                    overflow: TextOverflow.ellipsis,
                    maxLines: 1,
                  ),
                  const SizedBox(height: 2),
                  Text(
                    item.isDirectory
                        ? 'Folder'
                        : item.mimeType == 'application/octet-stream'
                        ? item.extension.isEmpty
                              ? 'File'
                              : '${item.extension.toUpperCase().replaceAll('.', '')} file'
                        : item.mimeType,
                    style: TextStyle(
                      color: cs.onSurfaceVariant,
                      fontSize: 11,
                    ),
                    overflow: TextOverflow.ellipsis,
                    maxLines: 1,
                  ),
                ],
              ),
            ),
          ],
        ),
        const SizedBox(height: 12),
        _metaRow('Size', item.formattedSize),
        _metaRow('Modified', item.formattedDate),
        _metaRow(
          'Type',
          item.extension.isEmpty
              ? 'Folder'
              : item.extension.toUpperCase().replaceAll('.', ''),
        ),
        _metaRow('Path', item.path),
      ],
    );
  }

  Widget _metaRow(String label, String value) {
    final cs = Theme.of(context).colorScheme;
    return Padding(
      padding: const EdgeInsets.only(bottom: 6),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 70,
            child: Text(
              label,
              style: TextStyle(color: cs.onSurfaceVariant, fontSize: 12),
            ),
          ),
          Expanded(
            child: Text(
              value,
              style: TextStyle(color: cs.onSurface, fontSize: 12),
            ),
          ),
        ],
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Top-level isolate entry points for the preview panel.
//
// These MUST be top-level functions (not methods or closures created inside
// the widget State). A closure defined inside a State method implicitly
// captures `this` — the whole rendered widget tree — and Isolate.run/compute
// then fails with "Illegal argument in isolate message: object is unsendable"
// (WidgetsFlutterBinding / RenderParagraph etc.). compute() + a top-level
// function reference sends only the String path across the boundary.
// ---------------------------------------------------------------------------

/// Reads a text/code/markdown file off the UI isolate. Caps reads at 512 KB
/// so a huge file never stalls either thread. Returns a marker when the file
/// is bigger than the cap.
String readTextCapped(String path) {
  final file = File(path);
  if (!file.existsSync()) return '[File not found]';
  final length = file.lengthSync();
  if (length > 512 * 1024) {
    final raf = file.openSync();
    try {
      final data = raf.readSync(512 * 1024);
      return '${utf8.decode(data, allowMalformed: true)}\n… (truncated)';
    } finally {
      raf.closeSync();
    }
  }
  return file.readAsStringSync();
}

/// DOCX text extraction for the preview panel. Reads the file itself from
/// [sourcePath] — no [File] objects cross the isolate boundary.
/// Returns `[File not found]` / `[File too large to preview]` /
/// `[No text content found]` placeholders instead of throwing.
String docxTextFromPath(String sourcePath) {
  try {
    final file = File(sourcePath);
    if (!file.existsSync()) return '[File not found]';
    if (file.lengthSync() > 8 * 1024 * 1024) {
      return '[File too large to preview]';
    }
    final bytes = file.readAsBytesSync();
    final archive = ZipDecoder().decodeBytes(bytes);
    final docXml = archive.findFile('word/document.xml');
    if (docXml == null) return '[No text content found]';
    // readBytes() — the `content` getter is unreliable in archive 4.x
    // (can yield empty bytes for stored / unsupported-compression entries).
    final docXmlBytes = docXml.readBytes();
    if (docXmlBytes == null) {
      return '[Could not read document: unsupported compression]';
    }
    var xml = utf8.decode(docXmlBytes, allowMalformed: true);
    // Paragraph and row endings → newlines, then strip all remaining tags.
    xml = xml
        .replaceAll('</w:p>', '\n')
        .replaceAll('</w:tr>', '\n')
        .replaceAll('<w:tab/>', '\t')
        .replaceAll(RegExp(r'<[^>]+>'), '');
    return xml
        .replaceAll('&amp;', '&')
        .replaceAll('&lt;', '<')
        .replaceAll('&gt;', '>')
        .replaceAll('&quot;', '"')
        .replaceAll('&apos;', "'")
        .trim();
  } catch (e) {
    return '[Could not read document: $e]';
  }
}

/// PPTX outline extractor for the preview panel. PPTX is a ZIP of slide XML
/// files (`ppt/slides/slide1.xml`, …). Picks the first few non-empty text
/// runs per slide. Output format:
///
///     Slide 1 — <title>
///       • <line>
///
/// Falls back to a friendly message when the file isn't a real PPTX or is
/// too large to parse cheaply.
String pptxOutlineFromPath(String sourcePath) {
  try {
    final file = File(sourcePath);
    if (!file.existsSync()) return '[File not found]';
    if (file.lengthSync() > 16 * 1024 * 1024) {
      return '[File too large to preview]';
    }
    final bytes = file.readAsBytesSync();
    final archive = ZipDecoder().decodeBytes(bytes);
    final slideFiles = archive.files
        .where((f) =>
            f.name.startsWith('ppt/slides/slide') && f.name.endsWith('.xml'))
        .toList()
      ..sort((a, b) => a.name.compareTo(b.name));
    if (slideFiles.isEmpty) return '[No slides found]';
    final buf = StringBuffer();
    const maxLinesPerSlide = 6;
    for (final slide in slideFiles) {
      // readBytes() — archive 4.x-safe content read (see docxTextFromPath).
      final slideBytes = slide.readBytes();
      if (slideBytes == null) continue;
      final xml = utf8.decode(slideBytes, allowMalformed: true);
      // Extract text inside <a:t>…</a:t>; the standard PPTX text element.
      final runs = RegExp(r'<a:t[^>]*>([^<]*)</a:t>')
          .allMatches(xml)
          .map((m) => m.group(1)?.trim() ?? '')
          .where((s) => s.isNotEmpty)
          .toList();
      final label = 'Slide ${_slideNumber(slide.name)}';
      if (runs.isEmpty) {
        buf.writeln('$label — (empty)');
        buf.writeln();
        continue;
      }
      // First non-empty run is treated as the slide title; the rest as
      // bullets. This is a heuristic but matches what most slides look like.
      buf.writeln('$label — ${runs.first}');
      for (final r in runs.skip(1).take(maxLinesPerSlide)) {
        buf.writeln('  • $r');
      }
      buf.writeln();
    }
    return buf.toString().trim();
  } catch (e) {
    return '[Could not read presentation: $e]';
  }
}

String _slideNumber(String name) {
  final m = RegExp(r'slide(\d+)\.xml$').firstMatch(name);
  return m?.group(1) ?? '?';
}

/// A single PDF page preview with zoom +/- buttons and fullscreen button.
/// Replaces InteractiveViewer (which ate taps) with explicit controls.
class _PdfPagePreview extends StatefulWidget {
  final String thumbPath;
  final int pageIndex;
  final int pageCount;
  final bool capped;
  final int maxPreview;
  final VoidCallback onFullScreen;

  const _PdfPagePreview({
    required this.thumbPath,
    required this.pageIndex,
    required this.pageCount,
    required this.capped,
    required this.maxPreview,
    required this.onFullScreen,
  });

  @override
  State<_PdfPagePreview> createState() => _PdfPagePreviewState();
}

class _PdfPagePreviewState extends State<_PdfPagePreview> {
  double _scale = 1.0;

  void _zoomIn() => setState(() => _scale = (_scale + 0.5).clamp(1.0, 6.0));
  void _zoomOut() => setState(() => _scale = (_scale - 0.5).clamp(1.0, 6.0));

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Entire page thumbnail is tappable — opens fullscreen reader
          Material(
            color: cs.surface,
            borderRadius: BorderRadius.circular(6),
            child: InkWell(
              onTap: widget.onFullScreen,
              borderRadius: BorderRadius.circular(6),
              child: ClipRRect(
                borderRadius: BorderRadius.circular(6),
                child: Transform.scale(
                  scale: _scale,
                  alignment: Alignment.topCenter,
                  child: Image.file(
                    File(widget.thumbPath),
                    fit: BoxFit.contain,
                    width: double.infinity,
                    errorBuilder: (_, _, _) => const Padding(
                      padding: EdgeInsets.all(24),
                      child: Icon(Icons.broken_image, size: 48),
                    ),
                  ),
                ),
              ),
            ),
          ),
          const SizedBox(height: 6),
          // Page label + zoom controls + fullscreen — all simple taps
          Row(
            children: [
              Text(
                'Page ${widget.pageIndex + 1}'
                '${widget.capped ? " / ${widget.pageCount}" : (widget.pageCount > 1 ? " / ${widget.pageCount}" : "")}',
                style: TextStyle(color: cs.onSurfaceVariant, fontSize: 11),
              ),
              const Spacer(),
              _zoomBtn(Icons.remove, cs, _zoomOut),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 6),
                child: Text(
                  '${(_scale * 100).round()}%',
                  style: TextStyle(color: cs.onSurfaceVariant, fontSize: 11),
                ),
              ),
              _zoomBtn(Icons.add, cs, _zoomIn),
              const SizedBox(width: 8),
              SizedBox(
                height: 28,
                child: FilledButton.tonalIcon(
                  onPressed: widget.onFullScreen,
                  icon: const Icon(Icons.fullscreen, size: 14),
                  label: const Text('Open', style: TextStyle(fontSize: 11)),
                  style: FilledButton.styleFrom(
                    padding: const EdgeInsets.symmetric(horizontal: 8),
                    minimumSize: Size.zero,
                    tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _zoomBtn(IconData icon, ColorScheme cs, VoidCallback onTap) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(4),
      child: Container(
        padding: const EdgeInsets.all(6),
        decoration: BoxDecoration(
          color: cs.surfaceContainerHighest,
          borderRadius: BorderRadius.circular(4),
        ),
        child: Icon(icon, size: 14, color: cs.onSurface),
      ),
    );
  }
}

/// Image preview with zoom controls and fullscreen button.
class _ImagePreviewTile extends StatefulWidget {
  final FileItem item;
  final VoidCallback onFullScreen;

  const _ImagePreviewTile({
    required this.item,
    required this.onFullScreen,
  });

  @override
  State<_ImagePreviewTile> createState() => _ImagePreviewTileState();
}

class _ImagePreviewTileState extends State<_ImagePreviewTile> {
  double _scale = 1.0;

  void _zoomIn() => setState(() => _scale = (_scale + 0.5).clamp(1.0, 6.0));
  void _zoomOut() => setState(() => _scale = (_scale - 0.5).clamp(1.0, 6.0));

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    return SingleChildScrollView(
      child: Column(
        children: [
          // Entire image is tappable — opens fullscreen viewer
          Material(
            color: cs.surface,
            borderRadius: BorderRadius.circular(6),
            child: InkWell(
              onTap: widget.onFullScreen,
              borderRadius: BorderRadius.circular(6),
              child: ClipRRect(
                borderRadius: BorderRadius.circular(6),
                child: Transform.scale(
                  scale: _scale,
                  alignment: Alignment.topCenter,
                  child: ConstrainedBox(
                    constraints: const BoxConstraints(maxHeight: 320),
                    child: Image.file(
                      File(widget.item.path),
                      fit: BoxFit.contain,
                      cacheWidth: 1000,
                      errorBuilder: (_, _, _) => Icon(
                        Icons.broken_image,
                        size: 48,
                        color: cs.onSurfaceVariant,
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
          const SizedBox(height: 8),
          // Zoom + fullscreen + open-with controls
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              _zoomBtn(Icons.remove, cs, _zoomOut),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 8),
                child: Text(
                  '${(_scale * 100).round()}%',
                  style: TextStyle(color: cs.onSurfaceVariant, fontSize: 12),
                ),
              ),
              _zoomBtn(Icons.add, cs, _zoomIn),
              const SizedBox(width: 12),
              SizedBox(
                height: 32,
                child: FilledButton.tonalIcon(
                  onPressed: widget.onFullScreen,
                  icon: const Icon(Icons.fullscreen, size: 14),
                  label: const Text('Open', style: TextStyle(fontSize: 11)),
                  style: FilledButton.styleFrom(
                    padding: const EdgeInsets.symmetric(horizontal: 8),
                    minimumSize: Size.zero,
                    tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          FilledButton.tonalIcon(
            onPressed: () async {
              try {
                await OpenWithService.openDefault(widget.item.path);
              } catch (_) {
                if (context.mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(
                      content: const Text("We couldn't find an app that opens this file type"),
                      backgroundColor: OneDarkColors.red,
                    ),
                  );
                }
              }
            },
            icon: const Icon(Icons.open_in_new, size: 16),
            label: const Text('Open with…'),
          ),
        ],
      ),
    );
  }

  Widget _zoomBtn(IconData icon, ColorScheme cs, VoidCallback onTap) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(4),
      child: Container(
        padding: const EdgeInsets.all(6),
        decoration: BoxDecoration(
          color: cs.surfaceContainerHighest,
          borderRadius: BorderRadius.circular(4),
        ),
        child: Icon(icon, size: 16, color: cs.onSurface),
      ),
    );
  }
}

/// Renders a video preview: a real frame thumbnail (extracted from the file
/// at ~1s in) overlaid with a big play button. Tapping opens the in-app
/// full-screen player. Falls back to a movie icon if the thumbnail cannot be
/// generated (corrupt file, unsupported codec, etc.).
class _VideoPreviewTile extends StatefulWidget {
  final String path;
  final String name;
  final VoidCallback onFullScreen;
  const _VideoPreviewTile({
    required this.path,
    required this.name,
    required this.onFullScreen,
  });

  @override
  State<_VideoPreviewTile> createState() => _VideoPreviewTileState();
}

class _VideoPreviewTileState extends State<_VideoPreviewTile> {
  String? _thumbPath;
  bool _thumbFailed = false;

  // Inline player state. Initialized lazily on first tap so we don't decode
  // a 1GB video the moment the user selects a file.
  VideoPlayerController? _controller;
  bool _controllerReady = false;
  String? _controllerError;
  bool _muted = true; // start muted to avoid surprise audio

  @override
  void initState() {
    super.initState();
    _generateThumb();
  }

  Future<void> _generateThumb() async {
    try {
      final tmp = await VideoThumbnail.thumbnailFile(
        video: widget.path,
        imageFormat: ImageFormat.JPEG,
        maxWidth: 480,
        quality: 70,
      );
      if (!mounted) return;
      setState(() => _thumbPath = tmp);
    } catch (_) {
      if (!mounted) return;
      setState(() => _thumbFailed = true);
    }
  }

  Future<void> _ensureController() async {
    if (_controller != null) return;
    final c = VideoPlayerController.file(
      File(widget.path),
      videoPlayerOptions: VideoPlayerOptions(mixWithOthers: true),
    );
    _controller = c;
    try {
      // initialize() can hang on Android 14+ for some codecs (HEVC, certain
      // MKV variants). Race it against a 6-second timeout so the user sees
      // a usable error instead of a permanent spinner, and fall back to the
      // full-screen player which uses the same controller but with more
      // surface area for diagnostics.
      await c.initialize().timeout(
            const Duration(seconds: 6),
            onTimeout: () => throw TimeoutException(
                'VideoPlayerController.initialize timed out'),
          );
      await c.setVolume(_muted ? 0 : 1);
      if (!mounted) return;
      setState(() {
        _controllerReady = true;
        _controllerError = null;
      });
    } catch (e) {
      // Discard the failed controller so a tap-to-retry works.
      try {
        c.dispose();
      } catch (_) {}
      _controller = null;
      if (!mounted) return;
      setState(() => _controllerError = e.toString());
    }
  }

  Future<void> _togglePlay() async {
    await _ensureController();
    if (!_controllerReady || !mounted) return;
    final c = _controller!;
    if (c.value.isPlaying) {
      await c.pause();
    } else {
      await c.play();
    }
    if (mounted) setState(() {});
  }

  Future<void> _toggleMute() async {
    if (_controller == null) return;
    final next = !_muted;
    await _controller!.setVolume(next ? 0 : 1);
    if (!mounted) return;
    setState(() => _muted = next);
  }

  String _format(Duration d) {
    final h = d.inHours;
    final m = d.inMinutes.remainder(60).toString().padLeft(2, '0');
    final s = d.inSeconds.remainder(60).toString().padLeft(2, '0');
    return h > 0 ? '$h:$m:$s' : '$m:$s';
  }

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    final c = _controller;

    // Inline player is ready — render the live player with controls.
    if (_controllerReady && c != null) {
      return Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(4),
            child: AspectRatio(
              aspectRatio: c.value.aspectRatio == 0
                  ? 16 / 9
                  : c.value.aspectRatio,
              child: Container(
                color: Colors.black,
                child: Stack(
                  alignment: Alignment.bottomCenter,
                  children: [
                    Positioned.fill(
                      child: VideoPlayer(c),
                    ),
                    if (!c.value.isPlaying)
                      const Center(
                        child: Icon(
                          Icons.play_circle_filled,
                          size: 56,
                          color: Colors.white70,
                        ),
                      ),
                    Positioned(
                      left: 0,
                      right: 0,
                      bottom: 0,
                      child: Container(
                        decoration: const BoxDecoration(
                          gradient: LinearGradient(
                            begin: Alignment.topCenter,
                            end: Alignment.bottomCenter,
                            colors: [
                              Colors.transparent,
                              Colors.black54,
                            ],
                          ),
                        ),
                        padding: const EdgeInsets.fromLTRB(8, 12, 8, 6),
                        child: Row(
                          children: [
                            IconButton(
                              icon: Icon(
                                c.value.isPlaying
                                    ? Icons.pause
                                    : Icons.play_arrow,
                                color: Colors.white,
                              ),
                              onPressed: _togglePlay,
                              tooltip: c.value.isPlaying
                                  ? 'Pause'
                                  : 'Play',
                            ),
                            Expanded(
                              child: VideoProgressIndicator(
                                c,
                                allowScrubbing: true,
                                colors: VideoProgressColors(
                                  playedColor: cs.primary,
                                  bufferedColor: cs.onSurfaceVariant,
                                  backgroundColor: cs.outlineVariant,
                                ),
                              ),
                            ),
                            Text(
                              '${_format(c.value.position)} / ${_format(c.value.duration)}',
                              style: const TextStyle(
                                color: Colors.white,
                                fontSize: 10,
                              ),
                            ),
                            IconButton(
                              icon: Icon(
                                _muted ? Icons.volume_off : Icons.volume_up,
                                color: Colors.white,
                                size: 20,
                              ),
                              onPressed: _toggleMute,
                              tooltip: _muted ? 'Unmute' : 'Mute',
                            ),
                            IconButton(
                              icon: const Icon(
                                Icons.fullscreen,
                                color: Colors.white,
                                size: 20,
                              ),
                              onPressed: widget.onFullScreen,
                              tooltip: 'Open full screen',
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
          const SizedBox(height: 4),
          Text(
            widget.name,
            style: TextStyle(color: cs.onSurface, fontSize: 12),
            overflow: TextOverflow.ellipsis,
          ),
        ],
      );
    }

    // Controller is initializing (after a tap) — show progress.
    if (_controller != null && !_controllerReady && _controllerError == null) {
      return AspectRatio(
        aspectRatio: 16 / 9,
        child: Container(
          decoration: BoxDecoration(
            color: cs.surface,
            borderRadius: BorderRadius.circular(4),
          ),
          child: Center(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                CircularProgressIndicator(color: cs.primary),
                const SizedBox(height: 8),
                Text(
                  'Loading video…',
                  style: TextStyle(color: cs.onSurfaceVariant, fontSize: 12),
                ),
              ],
            ),
          ),
        ),
      );
    }

    // Controller errored.
    if (_controllerError != null) {
      return AspectRatio(
        aspectRatio: 16 / 9,
        child: Container(
          decoration: BoxDecoration(
            color: cs.surface,
            borderRadius: BorderRadius.circular(4),
          ),
          child: Center(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(Icons.error_outline, color: cs.error, size: 36),
                const SizedBox(height: 4),
                Text(
                  'Cannot play video',
                  style: TextStyle(color: cs.onSurface, fontSize: 12),
                ),
                const SizedBox(height: 4),
                Text(
                  'Tap to open in full screen',
                  style: TextStyle(color: cs.primary, fontSize: 11),
                ),
              ],
            ),
          ),
        ),
      );
    }

    // Initial state — show thumbnail + a play button. Tapping the play
    // button initializes the inline player.
    return GestureDetector(
      onTap: _togglePlay,
      child: Column(
        children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(4),
            child: ConstrainedBox(
              constraints: const BoxConstraints(maxHeight: 320),
              child: AspectRatio(
                aspectRatio: 16 / 9,
                child: Container(
                  width: double.infinity,
                  color: cs.surface,
                  child: Stack(
                    fit: StackFit.expand,
                    children: [
                      if (_thumbPath != null)
                        Image.file(
                          File(_thumbPath!),
                          fit: BoxFit.cover,
                          errorBuilder: (_, _, _) => Center(
                            child: Icon(Icons.movie,
                                size: 64, color: cs.primary),
                          ),
                        )
                      else if (_thumbFailed)
                        Center(
                          child: Icon(Icons.movie,
                              size: 64, color: cs.primary),
                        )
                      else
                        Center(
                          child: CircularProgressIndicator(
                              color: cs.primary),
                        ),
                      Center(
                        child: Container(
                          decoration: const BoxDecoration(
                            color: Colors.black54,
                            shape: BoxShape.circle,
                          ),
                          padding: const EdgeInsets.all(12),
                          child: const Icon(
                            Icons.play_arrow,
                            color: Colors.white,
                            size: 40,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
          const SizedBox(height: 4),
          Text(
            widget.name,
            style: TextStyle(color: cs.onSurface, fontSize: 12),
            overflow: TextOverflow.ellipsis,
          ),
          Text(
            'Tap to play in preview',
            style: TextStyle(color: cs.onSurfaceVariant, fontSize: 11),
          ),
        ],
      ),
    );
  }
}
